server:
  port: 8080
management:
  server:
    port: 8091
    ssl:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasks
    username: task-manager
    password: temp12t4
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
    locations: classpath:/db/migration
    baselineOnMigrate: true
    schemas: notifications
  sql:
    init:
      platform: mysql
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
